<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$this->htmlElement('body')->appendAttribute('class', 'universal-viewer play');
$title = $resource->displayTitle();
$creator = $resource->value('dcterms:creator', ['type' => 'literal']);
if ($creator) {
    $title .= ' - ' . $creator;
}


?>

    <div class="min-h-screen md:flex">
        <div class="flex-none w-full md:max-w-xs ">
            <?php echo $this->pageTitle($title); ?>
        </div>
        <div class="flex-1">
            <?php echo $this->solrDragon($resource); ?>
        </div>
    </div>

